-- Seed additional groups if not exist
insert into groups (name) values
  ('A6'),
  ('A7'),
  ('A9'),
  ('A10'),
  ('A12'),
  ('B1'),
  ('B2'),
  ('B3'),
  ('A13'),
  ('A14'),
  ('A15'),
  ('A16'),
  ('B8'),
  ('B9')
on conflict (name) do nothing;

-- Seed active A & B students
insert into students (full_name, group_id, status) values
  ('Alimov Husniddin', (select id from groups where name = 'A6'), 'active'),
  ('Samadov Muhammad', (select id from groups where name = 'A9'), 'active'),
  ('Bahriddinov Mehriddin', (select id from groups where name = 'A6'), 'active'),
  ('Jo’ramurodov Bahodir', (select id from groups where name = 'A6'), 'active'),
  ('Amirov Amirxon', (select id from groups where name = 'A15'), 'active'),
  ('Eshonqulov Abdulaziz', (select id from groups where name = 'A9'), 'active'),
  ('Davronov Salohiddin', (select id from groups where name = 'A9'), 'active'),
  ('Odiljonov Nurshod', (select id from groups where name = 'A6'), 'active'),
  ('Nasrullayev Muhammadsaid', (select id from groups where name = 'A9'), 'active'),
  ('Burxonov Bobir', (select id from groups where name = 'A9'), 'active'),
  ('Marupov Abduaziz', (select id from groups where name = 'A12'), 'active'),
  ('Hamroqulov Hojiakbar', (select id from groups where name = 'A9'), 'active'),
  ('To''raqulov Zohidjon', (select id from groups where name = 'A9'), 'active'),
  ('Ma''rufov Ahmad', (select id from groups where name = 'A10'), 'active'),
  ('Hasanov Asilbek', (select id from groups where name = 'A6'), 'active'),
  ('Ashrabov Ahmadjon', (select id from groups where name = 'A16'), 'active'),
  ('Kamoljonov Doniyorbek', (select id from groups where name = 'A10'), 'active'),
  ('Jabborova Mohlaroyim', (select id from groups where name = 'A13'), 'active'),
  ('Karimov Abdulloh', (select id from groups where name = 'A14'), 'active'),
  ('Izzatullayev Muhammadziyo', (select id from groups where name = 'A15'), 'active'),
  ('Nuriddinov Kamoliddin', (select id from groups where name = 'A12'), 'active'),
  ('Qurbonov Saidshox', (select id from groups where name = 'A9'), 'active'),
  ('Raximov Abduraxmon', (select id from groups where name = 'A9'), 'active'),
  ('Eshonqulov Alisher', (select id from groups where name = 'A9'), 'active'),
  ('Sheraliyev Bexruz', (select id from groups where name = 'A9'), 'active'),
  ('Maxmudov Samirbek', (select id from groups where name = 'A10'), 'active'),
  ('Majidova Shabnam', (select id from groups where name = 'A13'), 'active'),
  ('G''anixonov Muhammadxoji', (select id from groups where name = 'A9'), 'active'),
  ('Baxriddinov Zuxriddin', (select id from groups where name = 'A9'), 'active'),
  ('Xazratqulov Shoxrux', (select id from groups where name = 'A10'), 'active'),
  ('Raxmonov Islom', (select id from groups where name = 'A10'), 'active'),
  ('Abdumajidov Ahmadjon', (select id from groups where name = 'A10'), 'active'),
  ('Islomov Ibrohim', (select id from groups where name = 'A10'), 'active'),
  ('Sultonmurodov Muhammadsolih', (select id from groups where name = 'A10'), 'active'),
  ('Olimov Jafarxon', (select id from groups where name = 'A15'), 'active'),
  ('Solihov Abdulloh', (select id from groups where name = 'A13'), 'active'),
  ('Haydarov Hamidulloh', (select id from groups where name = 'A10'), 'active'),
  ('Fazliyev Najmiddin', (select id from groups where name = 'A12'), 'active'),
  ('Ibrohimova Zulfiya', (select id from groups where name = 'B8'), 'active'),
  ('Abdugafurov Yusufjon', (select id from groups where name = 'A12'), 'active'),
  ('Xurramov G''olibjon', (select id from groups where name = 'A13'), 'active'),
  ('Amonova Sevinchbonu', (select id from groups where name = 'B8'), 'active'),
  ('G''aniyev Oyatillo', (select id from groups where name = 'A13'), 'active'),
  ('O''tkirov Muhammadali', (select id from groups where name = 'A12'), 'active'),
  ('Tilakov Jaloliddin', (select id from groups where name = 'A12'), 'active'),
  ('Negmatullayev Ibodullo', (select id from groups where name = 'A12'), 'active'),
  ('Islomov Xusan', (select id from groups where name = 'A15'), 'active'),
  ('Nematov Mirzobek', (select id from groups where name = 'A12'), 'active'),
  ('Davronov Bobur', (select id from groups where name = 'A12'), 'active'),
  ('Alisherova Maknuna', (select id from groups where name = 'A13'), 'active'),
  ('Mahqulov Mirzohid', (select id from groups where name = 'B8'), 'active'),
  ('Zayniddinov Shexroz', (select id from groups where name = 'A13'), 'active'),
  ('Rustamov Abubakr', (select id from groups where name = 'B8'), 'active'),
  ('Amriddinov Najmiddin', (select id from groups where name = 'A13'), 'active'),
  ('Sirojiddinov Shohrux', (select id from groups where name = 'A13'), 'active'),
  ('Sirojiddinov Shaxzod', (select id from groups where name = 'A13'), 'active'),
  ('Soliyev Sardor', (select id from groups where name = 'A14'), 'active'),
  ('Zoxidov Sheroz', (select id from groups where name = 'B8'), 'active'),
  ('Burxonov Bexruz', (select id from groups where name = 'A14'), 'active'),
  ('Saidmurodov Shoxjahon', (select id from groups where name = 'A14'), 'active'),
  ('Ashurov Abdug''affor', (select id from groups where name = 'A15'), 'active'),
  ('Ortiqov Bexruz', (select id from groups where name = 'A14'), 'active'),
  ('O''ktamov Javoxir', (select id from groups where name = 'A14'), 'active'),
  ('Islomova Bibisora', (select id from groups where name = 'B9'), 'active'),
  ('Egamberdiyev Muhammad', (select id from groups where name = 'B8'), 'active'),
  ('Shukrullayev Ozodbek', (select id from groups where name = 'A15'), 'active'),
  ('Muxsinov Javohir', (select id from groups where name = 'A15'), 'active'),
  ('Salomov Xurshid', (select id from groups where name = 'A14'), 'active'),
  ('Erkinov Muhammadjon', (select id from groups where name = 'B9'), 'active'),
  ('Toxirov Matniyoz', (select id from groups where name = 'A15'), 'active'),
  ('Narzullayev Dilshod', (select id from groups where name = 'A15'), 'active'),
  ('Bahodirov Yusuf', (select id from groups where name = 'A15'), 'active'),
  ('Bahodirov Yusuf', (select id from groups where name = 'A15'), 'active'),
  ('Tolibov Amin', (select id from groups where name = 'A15'), 'active'),
  ('Maxkamova Gulsanam', (select id from groups where name = 'B9'), 'active'),
  ('Nasimov Sardor', (select id from groups where name = 'A15'), 'active'),
  ('Norqulov Suxrobbek', (select id from groups where name = 'B9'), 'active'),
  ('Dosmurodov Ismoil', (select id from groups where name = 'B9'), 'active'),
  ('Ochilov Muhammadraxim', (select id from groups where name = 'B9'), 'active'),
  ('Maqsadillayev Muslim', (select id from groups where name = 'B9'), 'active'),
  ('To''lqinov Abduqodir', (select id from groups where name = 'B9'), 'active'),
  ('Mavlonov Fazliddin', (select id from groups where name = 'B9'), 'active'),
  ('Sirojiddinov Jahongir', (select id from groups where name = 'B9'), 'active'),
  ('Sodiqov Elnur', (select id from groups where name = 'B9'), 'active'),
  ('Matlabov Azizbek', (select id from groups where name = 'B9'), 'active'),
  ('Matlobov Xikmat', (select id from groups where name = 'B9'), 'active'),
  ('Marotov Akobir', (select id from groups where name = 'B9'), 'active'),
  ('Akbarov Ismoil', (select id from groups where name = 'A14'), 'active'),
  ('Ulug''bekov Amir', (select id from groups where name = 'A15'), 'active'),
  ('Jabbarov Abdukarim', (select id from groups where name = 'A16'), 'active'),
  ('Qahorov Usmon', (select id from groups where name = 'A15'), 'active'),
  ('Rustamov Xurshid', (select id from groups where name = 'A16'), 'active'),
  ('Barotov Firdavs', (select id from groups where name = 'A16'), 'active'),
  ('Baxrullayev Xushnud', (select id from groups where name = 'A16'), 'active'),
  ('Narzullayev Jahongir', (select id from groups where name = 'A16'), 'active'),
  ('Karimov Muhammadyusuf', (select id from groups where name = 'A16'), 'active'),
  ('Solixjonov Javoxir', (select id from groups where name = 'A16'), 'active'),
  ('Matlabov Kamron', (select id from groups where name = 'A16'), 'active'),
  ('Hakimov Islom', (select id from groups where name = 'A15'), 'active'),
  ('Muradillayev Ramziddin', (select id from groups where name = 'A16'), 'active'),
  ('Sattorov Mironshox', (select id from groups where name = 'A14'), 'active'),
  ('Kamolov Muhammadsodiq', (select id from groups where name = 'A16'), 'active'),
  ('Rajabqulov Zahriddin', (select id from groups where name = 'A16'), 'active'),
  ('Ashrabov Islom', (select id from groups where name = 'A16'), 'active'),
  ('Voxobov Muhammadali', (select id from groups where name = 'A16'), 'active'),
  ('Sadriddinov Sabriddin', (select id from groups where name = 'A16'), 'active'),
  ('Mahmatqulov Muhammadamin', (select id from groups where name = 'A14'), 'active'),
  ('O''ktamov Abduhamid', (select id from groups where name = 'A16'), 'active'),
  ('Maxkamov Amirjon', (select id from groups where name = 'A16'), 'active');